### ISSUE TITLE
Can't make the save work after modified it. 

### ISSUE THREAD

**Issue by MagicalTinFoil** [GarnetSunset/rgg_save_tool_py#1]
Hi GarnetSunset,

First of all, I have to say thank you so much for the effort in coding it an python. Thank you soooooooo much. 🤩
I tried the code, got the Hex file perfectly. 
However, After I modified the save and re-encrypt it, the save file won't work in the game. 
All all modified it's the money field.(I was playing ishin, and I hate chicken🤪)
I locate it by finding the money value in hex and search for it. 

I tried to remove the "ik" item from adding to the json object, and manually set it in the code for usage. 
Also, I tried print the last 4 bytes for the decrypted file data, and compare with the checksum used in encryption, which doesn't match. 
(Those might not be related since the code works perfectly without me extra modifying the money field). 

I wonder if there is some extra check/encryption on the money field that I can't understand. If you got any idea, suggestion, advise, please feel free to let me know.

Thanks!

**Comment by GarnetSunset** [comment]
Can you give me the save please?

**Comment by MagicalTinFoil** [comment]
Sure, thanks, I will get it to you after work. WOW, from the master himself! 😆

**Comment by GarnetSunset** [comment]
:) happy to support my projects!!

**Comment by MagicalTinFoil** [comment]
[data.zip](https://github.com/GarnetSunset/rgg_save_tool_py/files/13517984/data.zip)

**Comment by GarnetSunset** [comment]
which game is this btw

**Comment by GarnetSunset** [comment]
Oh it's ishin kiwami... yeah uhhh i might need to add a thing so that it doesnt try to jsonify the save

**Comment by GarnetSunset** [comment]
Do me a favor and try this?
https://github.com/GarnetSunset/rgg_save_tool_py/blob/main/rgg_save_tool.py

**Comment by MagicalTinFoil** [comment]
sure!

**Comment by MagicalTinFoil** [comment]
Seem like something wrong with the code. I just tried decrypt and re-encrypt the save file. Game notice me that it can't load it.

**Comment by MagicalTinFoil** [comment]
Maybe something with decryption?
Here is what I got from data.sav.json: 
![image](https://github.com/GarnetSunset/rgg_save_tool_py/assets/134741062/f7a502ee-7954-4d31-8705-c9bb2d30b8a7)

**Comment by GarnetSunset** [comment]
![image](https://github.com/GarnetSunset/rgg_save_tool_py/assets/13430434/5c93b776-b750-4dc3-b4df-077425cc5113)
That looks exactly like the save you sent me

**Comment by MagicalTinFoil** [comment]
yes, but that's the json file, not .sav

**Comment by MagicalTinFoil** [comment]
I think in line 100, parameter decrypted_data was never write back to replace data. That might be the issue.

**Comment by GarnetSunset** [comment]
You're right! Fixed!

**Comment by MagicalTinFoil** [comment]
oh, I just realized I send the screen shot of wrong window. XD sorry for the confusion.

**Comment by MagicalTinFoil** [comment]
I just saw the update, I will test it!

**Comment by MagicalTinFoil** [comment]
There is another issue, can't encrypt the file. I guess this is caused by the decrypted json file doesn't contain the normal file header. Therefore, <<< extension == ".json" and game_abbr != "ik" >>> is true. 
And, hence json.load() would fail due to 
"UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3560: character maps to <undefined>"
![image](https://github.com/GarnetSunset/rgg_save_tool_py/assets/134741062/0b5efa0d-3fed-443d-b6dc-4337b4b4e96b)

**Comment by GarnetSunset** [comment]
Fixed!

**Comment by MagicalTinFoil** [comment]
Wonderful! I just tried decrypt and re-encrypt the file, it worked!
I will try to modify the json file next.

**Comment by GarnetSunset** [comment]
Gotcha! I guess json isnt the correct term since its hex, i might change it to be .hex for ik and then make that the detector

**Comment by MagicalTinFoil** [comment]
Well, unfortunately, still, modify the money will cause the file not to be able to be used by the game. Why would they put so much effort on encrypting this??!😭

**Comment by MagicalTinFoil** [comment]
Man, thank you so much for your effort and dedication. Your project deserve more appreciation!

**Comment by GarnetSunset** [comment]
Thank you! I just wanna make this easier for everyone!!
