### ISSUE TITLE
Ishin (ps4) save decryption

### ISSUE THREAD

**Issue by bucanero** [GarnetSunset/rgg_save_tool_py#2]
Hi,

not an issue; just wanted to share that based on this repository and notes, I made a small tool to decrypt/encrypt/update checksum for `Like a dragon: Ishin!` PS4 save-games. Here's the source:
https://github.com/bucanero/save-decrypters/tree/master/rgg-decrypter

Xor Key is the same, the only difference is the final block with the crc32. In the ps4 save, the last 16 bytes are not encrypted and at `0x2F508` you need to update the crc32 (saved as little-endian).

**Comment by GarnetSunset** [comment]
Badass!! Huge fan of your work!! I might try to re-do this into python :)

**Comment by GarnetSunset** [comment]
Is it possible, since I don't have any, to get an example of a save? :O

**Comment by bucanero** [comment]
> Is it possible, since I don't have any, to get an example of a save? :O

happy to help, feel free to add this to your tool too 👍 

sure, here are some PS4 sample files: https://github.com/bucanero/save-decrypters/tree/master/rgg-decrypter/samples
(encrypted and decrypted versions of the same save)

**Comment by GarnetSunset** [comment]
Thank you!!

**Comment by GarnetSunset** [comment]
https://github.com/GarnetSunset/rgg_save_tool_py/commit/608828c1c2b89a9695113c840910e271c23327c3

Here we go!

**Comment by bucanero** [comment]
> [608828c](https://github.com/GarnetSunset/rgg_save_tool_py/commit/608828c1c2b89a9695113c840910e271c23327c3)
> 
> Here we go!

cool! 🎉  
Just a comment, the `crc32b()` method is the same as your `zlib.crc32()`, you can validate that by checking the CRC results for the same buffer, both methods will return an equal value. So feel free to remove it and keep your own `crc32_checksum()` 

( I used a simple crc32 implementation because I was building the tool in C and didn't want to import external libraries. )

**Comment by GarnetSunset** [comment]
Thank you! I don't know that!!
