### ISSUE TITLE
Need a Yakuza 0 and Yakuza Kiwami Steam to GOG converter

### ISSUE THREAD

**Issue by 50Assassin** [GarnetSunset/rgg_save_tool_py#4]
For some reason Steam Save files from 0 and Kiwami don't work on the GOG version, would you be able to make a Steam to GoG converter?

**Comment by GarnetSunset** [comment]
Find me on discord and I'll help you out. same name as on here. I'm also in
the yakuza modding discord. Whatever I figure out will be used to improve
the tool here.

**Comment by GarnetSunset** [comment]
Tested with the user, no plan to support since theres no checksum. And figured out the issue.
