### ISSUE TITLE
urecognized argument error

### ISSUE THREAD

**Issue by halebop17** [GarnetSunset/rgg_save_tool_py#7]
Your tool would save my life. Trying to convert a GOG Y7 save to steam. I keep getting unrecognized argument error for:
rgg_save_tool-windows.exe [--to-steam] [-g {y7_gog}] input_file.sav [output_file.sav].

What am I doing wrong?

**Comment by GarnetSunset** [comment]
you dont need to use the --to-steam option actually! I should clarify that in the readme/args. You just need to load your save with the tool into a json, and back into steam
