### ISSUE TITLE
Wrong checksum for Yakuza 6's encoding

### ISSUE THREAD

**Issue by pjeanjean** [GarnetSunset/rgg_save_tool_py#8]
Hi!

I just found your tool, and tried to use it to unlock Legend Mode with Yakuza 6.
While the decoding worked fine, the encoding did not seem accurate (I would get a different md5 after decoding and re-encoding a save), and the game would silently delete my modified save file.

When comparing a "normal" save and one encoded with this tool, I noticed that the checksums at the end were different.
This led me to your previous C implementation, and it seems that you had a [specific checksum calculation](https://github.com/GarnetSunset/rgg_save_tools/blob/master/y6_encrypt.c#L25) for Yakuza 6, that was not ported to the Python version.

Using the C version, I still managed to do what I wanted, so thanks a lot for that. I just wanted to report this in case someone else has the same issue.

**Comment by GarnetSunset** [comment]
Woah hey! Thank you for this! I appreciate this info! I'll research this and see what I can do.

**Comment by pjeanjean** [comment]
Sure: [save.zip](https://github.com/user-attachments/files/18169245/save.zip)

As you can see, if I decrypt it and encrypt it back, the checksum ends up being different
![image](https://github.com/user-attachments/assets/f63f5d57-6c50-43fc-9b9b-b1d183ac5820)

I'm testing this on ArchLinux.

https://github.com/GarnetSunset/rgg_save_tools/blob/master/y6_encrypt.c works fine, however.

**Comment by GarnetSunset** [comment]
Pushed an update that should fix your problem! Feel free to let me know if it works out!

**Comment by pjeanjean** [comment]
I just tested it with all my saves to be thorough, everything went fine. Thanks a lot!
