### ISSUE TITLE
.json can't be encrypted back to data.sav for Like a dragon infinite wealth

### ISSUE THREAD

**Issue by bluemoon27112** [GarnetSunset/rgg_save_tool_py#9]
I can drag my infinite wealth data.sav onto rgg_save_tool-windows.exe which outputs a data_y8.json.
Then dragging the .json doesn't convert back to data.sav.

**Comment by GarnetSunset** [comment]
Can you drop me your save?

**Comment by bluemoon27112** [comment]
[data.zip](https://github.com/user-attachments/files/18264118/data.zip)

**Comment by GarnetSunset** [comment]
Strange, Ill check the patterns for this file, thanks!
